### ISSUE TITLE
Lost can-connection with canboat.js

### ISSUE THREAD

**Issue by kdschmidt1** [SignalK/signalk-server#1557]
hello signalk-team,
After updating to 1.46.3 my can-connection with canboatjs on raspberry-pi is no longer working (but working on my Ubuntu desktop machine!).
I get the following errors:

{ Error: Cannot find module 'socketcan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at new CanbusStream (/usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/canbus.js:74:22)
    at CanbusStream (/usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/canbus.js:47:12)
    at Object.nmea2000input [as NMEA2000] (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/simple.js:233:30)
    at new Simple (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/simple.js:79:34)
    at createPipeElement (/usr/lib/node_modules/signalk-server/lib/pipedproviders.js:75:16)
    at result.pipeElements.providerConfig.pipeElements.reduce (/usr/lib/node_modules/signalk-server/lib/pipedproviders.js:48:30)
    at Array.reduce (<anonymous>)
    at createPipedProvider (/usr/lib/node_modules/signalk-server/lib/pipedproviders.js:46:55)
    at app.config.settings.pipedProviders.reduce (/usr/lib/node_modules/signalk-server/lib/pipedproviders.js:82:37)
    at Array.reduce (<anonymous>)
    at Object.startProviders [as start] (/usr/lib/node_modules/signalk-server/lib/pipedproviders.js:79:62)
    at createServer (/usr/lib/node_modules/signalk-server/lib/index.js:280:66) code: 'MODULE_NOT_FOUND' }
WARNING unable to load native socketcan interface
signalk-server running at 0.0.0.0:3000

  canboatjs:canbus found socketcan-writer, starting... +0ms
ReferenceError: setProviderStatus is not defined
    at ChildProcess.CanbusStream.hasWriter.on.code (/usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/canbus.js:100:9)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)

Does anyone have an explanation and solution?
regards klaus

**Comment by sbender9** [comment]
Something went wrong with the canboatjs install,the socketcan module failed to install. 

Try a global install of canboatjs and capture the output. 

npm install -g @canboat/canboatjs

**Comment by kdschmidt1** [comment]
hello sbender,
i tried, but i had to run with sudo npm install -g --force @canboat/canboatjs to overcome all errors.
even after reboot the error in signalk-server remained!
see the output of operation below:

pi@raspberrypi:~ $ npm install -g @canboat/canboatjs
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/lib/node_modules/@canboat
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@canboat'
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@canboat']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, mkdir \'/usr/lib/node_modules/@canboat\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/lib/node_modules/@canboat' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2023-05-13T15_00_37_438Z-debug.log
pi@raspberrypi:~ $ sudo npm install -g @canboat/canboatjs
npm ERR! code EEXIST
npm ERR! path /usr/bin/ikonvert-serial
npm ERR! EEXIST: file already exists
npm ERR! File exists: /usr/bin/ikonvert-serial
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-05-13T15_02_00_990Z-debug.log
pi@raspberrypi:~ $ sudo npm install -g --force @canboat/canboatjs
npm WARN using --force Recommended protections disabled.

added 132 packages, and audited 133 packages in 2m

22 packages are looking for funding
  run `npm fund` for details

5 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.


regards klaus

**Comment by sbender9** [comment]
Sorry, forgot the sudo, so "sudo npm install ..."

This won't fix your issue but should tell us what is going wrong.

**Comment by kdschmidt1** [comment]
hi sbender,
as mentioned before i ran with sudo and also --force-install (see output before).
but starting signalk-server after reboot showed the same error as in my original posting.
regards klaus

**Comment by tkurki** [comment]
I would just retry installing everything with

`sudo npm install -g signalk-server`

**Comment by cmotelet** [comment]
I had a similar problem with a `raspbian strech` when upgrading from signalk-server-1.45 to signalk-server-1.46.3.
The pre-built module for `socketcan` does not seem to be available for this distribution.
To check and get more details, you can enter:
`sudo npm install -g socketcan`
In my case, npm tries to build the module but for that you need a minimum version of python >= 3.6 and the distribution stops at 3.5.
I had to build and install python3.9 from source ( https://tecadmin.net/how-to-install-python-3-9-on-debian-9/ ).
then:
`export PYTHON=/usr/local/bin/python3.9`
`npm install -g socketcan`
And everything is back in order.

**Comment by kdschmidt1** [comment]
Even  re-installing everything did not help, so i had to create a new openplotter image (v3) with a lot of configuration work, that is running properly now.
thanks to all and regards
klaus

**Comment by hans-martijn** [comment]
> I had a similar problem with a `raspbian strech` when upgrading from signalk-server-1.45 to signalk-server-1.46.3. The pre-built module for `socketcan` does not seem to be available for this distribution. To check and get more details, you can enter: `sudo npm install -g socketcan` In my case, npm tries to build the module but for that you need a minimum version of python >= 3.6 and the distribution stops at 3.5. I had to build and install python3.9 from source ( https://tecadmin.net/how-to-install-python-3-9-on-debian-9/ ). then: `export PYTHON=/usr/local/bin/python3.9` `npm install -g socketcan` And everything is back in order.

I had the same error with raspberrypios bookworm and the latest update from signalk. I got the error "WARNING unable to load native socketcan interface", which was immediately solved by installing socketcan. Thanks!!!

-hans
