### PR TITLE
fix: Fix `app.getFeatures` on startup

### PR DESCRIPTION
**Pull request by bkeepers**
This fixes the following error when a plugin calls `app.getFeatures` on startup. 

```
TypeError: app.getPluginsList is not a function
    at Server.app.getFeatures (/Users/bkeepers/projects/signalk/signalk-server/dist/index.js:86:36)
    at Object.start (/Users/bkeepers/projects/signalk/signalk-bathymetry/dist/index.js:26:35)
    at doPluginStart (/Users/bkeepers/projects/signalk/signalk-server/dist/interfaces/plugins.js:304:20)
    at doRegisterPlugin (/Users/bkeepers/projects/signalk/signalk-server/dist/interfaces/plugins.js:473:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async registerPlugin (/Users/bkeepers/projects/signalk/signalk-server/dist/interfaces/plugins.js:251:13)
    at async Promise.all (index 8)
    at async startPlugins (/Users/bkeepers/projects/signalk/signalk-server/dist/interfaces/plugins.js:198:9)
    at async Object.start (/Users/bkeepers/projects/signalk/signalk-server/dist/interfaces/plugins.js:36:13)
```

This error was introduced in https://github.com/SignalK/signalk-server/pull/1913. The issue is that that `src/interfaces/plugins.ts` is now awaiting the call to `startPlugins(theApp)`, and then defines the `getPluginsList` after the plugins are loaded. This moves the `startPlugins` call to the end of that method after the method has been defined.

This also fixes the return type for `app.getFeatures`, which was missing a `Promise`, and removes a duplicate interface definition.

### CODE REVIEW

**Comment by tkurki** [comment]
@panaaj how does this look to you?

**Comment by panaaj** [comment]
@tkurki @bkeepers This looks OK to me.

**Review by panaaj — APPROVED** [review]

**Comment by bkeepers** [comment]
@tkurki This one should probably be merged before the release. I haven't noticed any of the plugins that I use break because of this, but I could imagine there could be some.
